version: '2'
services:
  geth:
    restart: always
    container_name: ethereum-node
    image: ethereum/client-go
    entrypoint: /bin/sh
    command: /root/files/${SOLON_ENV}/geth.sh
    volumes:
      - ./environments/geth/${SOLON_ENV}/geth.sh:/root/files/${SOLON_ENV}/geth.sh:ro
      - ./environments/geth/${SOLON_ENV}/password:/root/files/${SOLON_ENV}/password:ro
      - ./environments/geth/${SOLON_ENV}/genesis.json:/root/files/${SOLON_ENV}/genesis.json:ro
      - ./environments/geth/${SOLON_ENV}/keystore:/root/.ethereum/${SOLON_ENV}/keystore:rw
      - ./data/geth/${SOLON_ENV}:/root/.ethereum/${SOLON_ENV}:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
  ipfs:
    restart: always
    container_name: ipfs-node
    image: ipfs/go-ipfs
    volumes:
      - ./data/ipfs/staging:/export
      - ./data/ipfs/data:/data/ipfs
    ports:
      - "8080:8080"
      - "4001:4001"
      - "127.0.0.1:5001:5001"
