version: '2'
services:
  ipfs:
    restart: always
    container_name: ipfs-node
    image: ipfs/go-ipfs
    volumes:
    - ./data/ipfs/staging:/export
    - ./data/ipfs/data:/data/ipfs
    ports:
    - "8080:8080"
    - "4001:4001"
    - "127.0.0.1:5001:5001"
