export const WEB3 = {
  INIT_REQUEST: 'WEB3/INIT_REQUEST',
  INIT_FAILURE: 'WEB3/INIT_FAILURE',
  INIT_SUCCESS: 'WEB3/INIT_SUCCESS',
  NETWORK_REQUEST: 'WEB3/NETWORD_REQUEST',
  NETWORD_FAILURE: 'WEB3/NETWORD_FAILURE',
  NETWORD_SUCCESS: 'WEB3/NETWORD_SUCCESS'
};
