version: '2'
services:
  geth:
    restart: always
    container_name: ethereum-node
    image: ethereum/client-go
    entrypoint: /bin/sh
    command: /root/files/${SOLON_ENV}/geth.sh
    volumes:
    - ./data/geth/${SOLON_ENV}:/root/.ethereum/${SOLON_ENV}:rw
    - ./environments/geth/${SOLON_ENV}/geth.sh:/root/files/${SOLON_ENV}/geth.sh:ro
    ports:
    - "30303:30303"
    - "30303:30303/udp"
    - "8545:8545"
    - "8546:8546"
